# Generated by Django 4.2 on 2026-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pin_code',
            field=models.CharField(blank=True, db_index=True, max_length=4),
        ),
    ]
