# Generated by Django 4.2 on 2026-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='BSIT', max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(default=1),
        ),
    ]
